BITMAKER-1379: Add comand to return data in csv format
bitmakerla/bitmaker-cli pull request #8
Opened 2022-01-27 02:00 UTC by Adriana618

### Ticket URL:
- https://tasks.bitmaker.dev/issues/1379
### Description:
- Add comand to retrieve data in csv and json format:
> `bitmaker data job <jobID> <spiderID> <projectID> --format <format>` Default format is json,

2022-01-31 04:30 UTC, mgonnav requested changes

2022-01-31 04:30 UTC, mgonnav commented on bm_cli/bm_client.py
> +        return response
When creating jobs using the CLI, I'm getting `Error: Cannot create the job for given SID and PID.`. However, the job does create successfully. I guess this is the reason for that.

2022-02-01 17:17 UTC, Adriana618 commented on bm_cli/data/job.py
> +@click.option("-f", "--format", required=False)
Changed.

2022-02-01 17:17 UTC, Adriana618 commented on bm_cli/bm_client.py
> +        return response
Fixed.

2022-02-01 21:17 UTC, mgonnav approved these changes
Let's remove the `print` statement and it is good to merge.

2022-02-01 21:17 UTC, mgonnav commented on bm_cli/data/job.py
> +    print(format)
Let's remove this print 😅

2022-02-01 22:26 UTC, Adriana618 commented on bm_cli/data/job.py
> +    print(format)
Removed.

2022-02-01 22:27 UTC, merged